<?php
$FR_solution = array(
  6  =>
  array(
    'name'           => 'Alais',
    'year'           => '1806',
    'country'        => 'France',
    'departement_fr' => 'Gard',
    'recclass'       => 'CI1',
    'mass_g'         => 6000.0,
    'reclat'         => 44.11667,
    'reclong'        => 4.08333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 448,
  ),
  8  =>
  array(
    'name'           => 'Alby sur Chéran',
    'year'           => '2002',
    'country'        => 'France',
    'departement_fr' => 'Haute-Savoie',
    'recclass'       => 'Eucrite-mmict',
    'mass_g'         => 252.0,
    'reclat'         => 45.82133,
    'reclong'        => 6.01533,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 458,
  ),
  19 =>
  array(
    'name'           => 'Asco',
    'year'           => '1805',
    'country'        => 'France',
    'departement_fr' => 'Haute-Corse',
    'recclass'       => 'H6',
    'mass_g'         => 41.0,
    'reclat'         => 42.45,
    'reclong'        => 9.03333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 2345,
  ),
  25 =>
  array(
    'name'           => 'Barbotan',
    'year'           => '1790',
    'country'        => 'France',
    'departement_fr' => 'Gers',
    'recclass'       => 'H5',
    'mass_g'         => 6400.0,
    'reclat'         => 43.95,
    'reclong'        => -0.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 4942,
  ),
  35 =>
  array(
    'name'           => 'Beuste',
    'year'           => '1859',
    'country'        => 'France',
    'departement_fr' => 'Pyrénées-Atlantiques',
    'recclass'       => 'L5',
    'mass_g'         => 2000.0,
    'reclat'         => 43.21667,
    'reclong'        => -0.23333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5034,
  ),
  68 =>
  array(
    'name'           => 'Chantonnay',
    'year'           => '1812',
    'country'        => 'France',
    'departement_fr' => 'Indre',
    'recclass'       => 'L6',
    'mass_g'         => 31500.0,
    'reclat'         => 46.68333,
    'reclong'        => 1.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5325,
  ),
  69 =>
  array(
    'name'           => 'Château-Renard',
    'year'           => '1841',
    'country'        => 'France',
    'departement_fr' => 'Loiret',
    'recclass'       => 'L6',
    'mass_g'         => 30000.0,
    'reclat'         => 47.93333,
    'reclong'        => 2.91667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5332,
  ),
  96 =>
  array(
    'name'           => 'Ensisheim',
    'year'           => '1491',
    'country'        => 'France',
    'departement_fr' => 'Haut-Rhin',
    'recclass'       => 'LL6',
    'mass_g'         => 127000.0,
    'reclat'         => 47.86667,
    'reclong'        => 7.35,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 10039,
  ),
);
?>