<?php
$M2_solution = array(
  0  =>
  array(
    'name'           => 'Acapulco',
    'year'           => '1976',
    'country'        => 'Mexico',
    'departement_fr' => NULL,
    'recclass'       => 'Acapulcoite',
    'mass_g'         => 1914.0,
    'reclat'         => 16.88333,
    'reclong'        => -99.9,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MX',
    'id'             => 10,
  ),
  1  =>
  array(
    'name'           => 'Aioun el Atrouss',
    'year'           => '1974',
    'country'        => 'Mauritania',
    'departement_fr' => NULL,
    'recclass'       => 'Diogenite-pm',
    'mass_g'         => 1000.0,
    'reclat'         => 16.39806,
    'reclong'        => -9.57028,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MR',
    'id'             => 423,
  ),
  2  =>
  array(
    'name'           => 'Aïr',
    'year'           => '1925',
    'country'        => 'Niger',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 24000.0,
    'reclat'         => 19.08333,
    'reclong'        => 8.38333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'NE',
    'id'             => 424,
  ),
  3  =>
  array(
    'name'           => 'Akaba',
    'year'           => '1949',
    'country'        => 'Jordan',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 779.0,
    'reclat'         => 29.51667,
    'reclong'        => 35.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'JO',
    'id'             => 426,
  ),
  4  =>
  array(
    'name'           => 'Akyumak',
    'year'           => '1981',
    'country'        => 'Turkey',
    'departement_fr' => NULL,
    'recclass'       => 'Iron, IVA',
    'mass_g'         => 50000.0,
    'reclat'         => 39.91667,
    'reclong'        => 42.81667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'TR',
    'id'             => 433,
  ),
  5  =>
  array(
    'name'           => 'Al Rais',
    'year'           => '1957',
    'country'        => 'Saudi Arabia',
    'departement_fr' => NULL,
    'recclass'       => 'CR2-an',
    'mass_g'         => 160.0,
    'reclat'         => 24.41667,
    'reclong'        => 39.51667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'SA',
    'id'             => 446,
  ),
  6  =>
  array(
    'name'           => 'Alais',
    'year'           => '1806',
    'country'        => 'France',
    'departement_fr' => 'Gard',
    'recclass'       => 'CI1',
    'mass_g'         => 6000.0,
    'reclat'         => 44.11667,
    'reclong'        => 4.08333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 448,
  ),
  7  =>
  array(
    'name'           => 'Albareto',
    'year'           => '1766',
    'country'        => 'Italy',
    'departement_fr' => NULL,
    'recclass'       => 'L/LL4',
    'mass_g'         => 2000.0,
    'reclat'         => 44.65,
    'reclong'        => 11.01667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IT',
    'id'             => 453,
  ),
  8  =>
  array(
    'name'           => 'Alby sur Chéran',
    'year'           => '2002',
    'country'        => 'France',
    'departement_fr' => 'Haute-Savoie',
    'recclass'       => 'Eucrite-mmict',
    'mass_g'         => 252.0,
    'reclat'         => 45.82133,
    'reclong'        => 6.01533,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 458,
  ),
  9  =>
  array(
    'name'           => 'Alessandria',
    'year'           => '1860',
    'country'        => 'Italy',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 908.0,
    'reclat'         => 44.88333,
    'reclong'        => 8.75,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IT',
    'id'             => 463,
  ),
  10 =>
  array(
    'name'           => 'Alexandrovsky',
    'year'           => '1900',
    'country'        => 'Ukraine',
    'departement_fr' => NULL,
    'recclass'       => 'H4',
    'mass_g'         => 9251.0,
    'reclat'         => 50.95,
    'reclong'        => 31.81667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'UA',
    'id'             => 465,
  ),
  11 =>
  array(
    'name'           => 'Alfianello',
    'year'           => '1883',
    'country'        => 'Italy',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 228000.0,
    'reclat'         => 45.26667,
    'reclong'        => 10.15,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IT',
    'id'             => 466,
  ),
  12 =>
  array(
    'name'           => 'Ambapur Nagla',
    'year'           => '1895',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 6400.0,
    'reclat'         => 27.66667,
    'reclong'        => 78.25,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 2290,
  ),
  13 =>
  array(
    'name'           => 'Andover',
    'year'           => '1898',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 3200.0,
    'reclat'         => 44.61667,
    'reclong'        => -70.75,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 2295,
  ),
  14 =>
  array(
    'name'           => 'Andreevka',
    'year'           => '1969',
    'country'        => 'Ukraine',
    'departement_fr' => NULL,
    'recclass'       => 'L3',
    'mass_g'         => 600.0,
    'reclat'         => 48.7,
    'reclong'        => 37.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'UA',
    'id'             => 2296,
  ),
  15 =>
  array(
    'name'           => 'Northwest Africa 5815',
    'year'           => NULL,
    'country'        => NULL,
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 256.8,
    'reclat'         => 0.0,
    'reclong'        => 0.0,
    'nametype'       => 'Valid',
    'fall'           => 'Found',
    'country_code'   => NULL,
    'id'             => 50693,
  ),
  16 =>
  array(
    'name'           => 'Angra dos Reis (stone)',
    'year'           => '1869',
    'country'        => NULL,
    'departement_fr' => NULL,
    'recclass'       => 'Angrite',
    'mass_g'         => 1500.0,
    'reclat'         => -22.96667,
    'reclong'        => -44.31667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => NULL,
    'id'             => 2302,
  ),
  17 =>
  array(
    'name'           => 'Archie',
    'year'           => '1932',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'H6',
    'mass_g'         => 5070.0,
    'reclat'         => 38.5,
    'reclong'        => -94.3,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 2329,
  ),
  18 =>
  array(
    'name'           => 'Arroyo Aguiar',
    'year'           => '1950',
    'country'        => 'Argentina',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 7450.0,
    'reclat'         => -31.41667,
    'reclong'        => -60.66667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AR',
    'id'             => 2340,
  ),
  19 =>
  array(
    'name'           => 'Asco',
    'year'           => '1805',
    'country'        => 'France',
    'departement_fr' => 'Haute-Corse',
    'recclass'       => 'H6',
    'mass_g'         => 41.0,
    'reclat'         => 42.45,
    'reclong'        => 9.03333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 2345,
  ),
  20 =>
  array(
    'name'           => 'Ash Creek',
    'year'           => '2009',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 9500.0,
    'reclat'         => 31.805,
    'reclong'        => -97.01,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 48954,
  ),
  21 =>
  array(
    'name'           => 'Atarra',
    'year'           => '1920',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'L4',
    'mass_g'         => 1280.0,
    'reclat'         => 25.25417,
    'reclong'        => 80.625,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 4883,
  ),
  22 =>
  array(
    'name'           => 'Athens',
    'year'           => '1933',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 265.0,
    'reclat'         => 34.75,
    'reclong'        => -87.0,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 4885,
  ),
  23 =>
  array(
    'name'           => 'Atoka',
    'year'           => '1945',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 1384.2,
    'reclat'         => 34.31667,
    'reclong'        => -96.15,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 4888,
  ),
  24 =>
  array(
    'name'           => 'Avilez',
    'year'           => '1855',
    'country'        => 'Mexico',
    'departement_fr' => NULL,
    'recclass'       => 'H',
    'mass_g'         => 146.0,
    'reclat'         => 25.0,
    'reclong'        => -103.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MX',
    'id'             => 4907,
  ),
  25 =>
  array(
    'name'           => 'Barbotan',
    'year'           => '1790',
    'country'        => 'France',
    'departement_fr' => 'Gers',
    'recclass'       => 'H5',
    'mass_g'         => 6400.0,
    'reclat'         => 43.95,
    'reclong'        => -0.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 4942,
  ),
  26 =>
  array(
    'name'           => 'Barnaul',
    'year'           => '1904',
    'country'        => 'Russia',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 23.2,
    'reclat'         => 52.73333,
    'reclong'        => 84.08333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RU',
    'id'             => 4947,
  ),
  27 =>
  array(
    'name'           => 'Baroti',
    'year'           => '1910',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 4500.0,
    'reclat'         => 31.61667,
    'reclong'        => 76.8,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 4949,
  ),
  28 =>
  array(
    'name'           => 'Bassikounou',
    'year'           => '2006',
    'country'        => 'Mauritania',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 29560.0,
    'reclat'         => 15.78333,
    'reclong'        => -5.9,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MR',
    'id'             => 44876,
  ),
  29 =>
  array(
    'name'           => 'Baszkówka',
    'year'           => '1994',
    'country'        => 'Poland',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 15500.0,
    'reclat'         => 52.03333,
    'reclong'        => 20.93583,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'PL',
    'id'             => 4957,
  ),
  30 =>
  array(
    'name'           => 'Bath',
    'year'           => '1892',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'H4',
    'mass_g'         => 21000.0,
    'reclat'         => 45.41667,
    'reclong'        => -98.31667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 4974,
  ),
  31 =>
  array(
    'name'           => 'Bawku',
    'year'           => '1989',
    'country'        => 'Ghana',
    'departement_fr' => NULL,
    'recclass'       => 'LL5',
    'mass_g'         => 1557.0,
    'reclat'         => 11.08333,
    'reclong'        => -0.18333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'GH',
    'id'             => 4976,
  ),
  32 =>
  array(
    'name'           => 'Baxter',
    'year'           => '1916',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 611.0,
    'reclat'         => 36.75,
    'reclong'        => -93.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 4977,
  ),
  33 =>
  array(
    'name'           => 'Beaver Creek',
    'year'           => '1893',
    'country'        => 'Canada',
    'departement_fr' => 'Columbia-Shuswap',
    'recclass'       => 'H5',
    'mass_g'         => 14000.0,
    'reclat'         => 51.16667,
    'reclong'        => -117.33333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CA',
    'id'             => 4986,
  ),
  34 =>
  array(
    'name'           => 'Berlanguillas',
    'year'           => '1811',
    'country'        => 'Spain',
    'departement_fr' => 'Burgos',
    'recclass'       => 'L6',
    'mass_g'         => 1440.0,
    'reclat'         => 41.68333,
    'reclong'        => -3.8,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'ES',
    'id'             => 5029,
  ),
  35 =>
  array(
    'name'           => 'Beuste',
    'year'           => '1859',
    'country'        => 'France',
    'departement_fr' => 'Pyrénées-Atlantiques',
    'recclass'       => 'L5',
    'mass_g'         => 2000.0,
    'reclat'         => 43.21667,
    'reclong'        => -0.23333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5034,
  ),
  36 =>
  array(
    'name'           => 'Bhola',
    'year'           => '1940',
    'country'        => 'Bangladesh',
    'departement_fr' => NULL,
    'recclass'       => 'LL3-6',
    'mass_g'         => 1047.0,
    'reclat'         => 22.68333,
    'reclong'        => 90.65,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'BD',
    'id'             => 5040,
  ),
  37 =>
  array(
    'name'           => 'Bialystok',
    'year'           => '1827',
    'country'        => 'Poland',
    'departement_fr' => NULL,
    'recclass'       => 'Eucrite-pmict',
    'mass_g'         => 4000.0,
    'reclat'         => 53.1,
    'reclong'        => 23.2,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'PL',
    'id'             => 5042,
  ),
  38 =>
  array(
    'name'           => 'Bilanga',
    'year'           => '1999',
    'country'        => 'Burkina Faso',
    'departement_fr' => NULL,
    'recclass'       => 'Diogenite',
    'mass_g'         => 25000.0,
    'reclat'         => 12.45,
    'reclong'        => -0.08333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'BF',
    'id'             => 5045,
  ),
  39 =>
  array(
    'name'           => 'Bishunpur',
    'year'           => '1895',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'LL3.15',
    'mass_g'         => 1039.0,
    'reclat'         => 25.38333,
    'reclong'        => 82.6,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 5060,
  ),
  40 =>
  array(
    'name'           => 'Bjurböle',
    'year'           => '1899',
    'country'        => 'Finland',
    'departement_fr' => NULL,
    'recclass'       => 'L/LL4',
    'mass_g'         => 330000.0,
    'reclat'         => 60.4,
    'reclong'        => 25.8,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FI',
    'id'             => 5064,
  ),
  41 =>
  array(
    'name'           => 'Black Moshannan Park',
    'year'           => '1941',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 705.0,
    'reclat'         => 40.91667,
    'reclong'        => -78.08333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5065,
  ),
  42 =>
  array(
    'name'           => 'Bocas',
    'year'           => '1804',
    'country'        => 'Mexico',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 56.0,
    'reclat'         => 23.0,
    'reclong'        => -102.0,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MX',
    'id'             => 5093,
  ),
  43 =>
  array(
    'name'           => 'Boguslavka',
    'year'           => '1916',
    'country'        => 'Russia',
    'departement_fr' => NULL,
    'recclass'       => 'Iron, IIAB',
    'mass_g'         => 256000.0,
    'reclat'         => 44.55,
    'reclong'        => 131.63333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RU',
    'id'             => 5098,
  ),
  44 =>
  array(
    'name'           => 'Borgo San Donino',
    'year'           => '1808',
    'country'        => 'Italy',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 1676.0,
    'reclat'         => 44.86667,
    'reclong'        => 10.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IT',
    'id'             => 5110,
  ),
  45 =>
  array(
    'name'           => 'Boriskino',
    'year'           => '1930',
    'country'        => 'Russia',
    'departement_fr' => NULL,
    'recclass'       => 'CM2',
    'mass_g'         => 1342.0,
    'reclat'         => 54.23333,
    'reclong'        => 52.48333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RU',
    'id'             => 5112,
  ),
  46 =>
  array(
    'name'           => 'Borkut',
    'year'           => '1852',
    'country'        => 'Ukraine',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 7000.0,
    'reclat'         => 48.15,
    'reclong'        => 24.28333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'UA',
    'id'             => 5113,
  ),
  47 =>
  array(
    'name'           => 'Borodino',
    'year'           => '1812',
    'country'        => 'Russia',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 500.0,
    'reclat'         => 55.46667,
    'reclong'        => 35.86667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RU',
    'id'             => 5114,
  ),
  48 =>
  array(
    'name'           => 'Boumdeid (2003)',
    'year'           => '2003',
    'country'        => 'Mauritania',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 190.0,
    'reclat'         => 17.71067,
    'reclong'        => -11.3715,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MR',
    'id'             => 57168,
  ),
  49 =>
  array(
    'name'           => 'Breitscheid',
    'year'           => '1956',
    'country'        => 'Germany',
    'departement_fr' => 'Landkreis Lahn-Dill-Kreis',
    'recclass'       => 'H5',
    'mass_g'         => 1500.0,
    'reclat'         => 50.66694,
    'reclong'        => 8.18361,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'DE',
    'id'             => 5134,
  ),
  50 =>
  array(
    'name'           => 'Bruderheim',
    'year'           => '1960',
    'country'        => 'Canada',
    'departement_fr' => 'Division No. 10',
    'recclass'       => 'L6',
    'mass_g'         => 303000.0,
    'reclat'         => 53.9,
    'reclong'        => -112.88333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CA',
    'id'             => 5156,
  ),
  51 =>
  array(
    'name'           => 'Bustee',
    'year'           => '1852',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'Aubrite',
    'mass_g'         => 1500.0,
    'reclat'         => 26.78333,
    'reclong'        => 82.83333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 5181,
  ),
  52 =>
  array(
    'name'           => 'Cabezo de Mayo',
    'year'           => '1870',
    'country'        => 'Spain',
    'departement_fr' => 'Murcia',
    'recclass'       => 'L/LL6',
    'mass_g'         => 25000.0,
    'reclat'         => 37.98333,
    'reclong'        => -1.16667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'ES',
    'id'             => 5185,
  ),
  53 =>
  array(
    'name'           => 'Cabin Creek',
    'year'           => '1886',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'Iron, IIIAB',
    'mass_g'         => 48500.0,
    'reclat'         => 35.5,
    'reclong'        => -93.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5186,
  ),
  54 =>
  array(
    'name'           => 'Cacak',
    'year'           => '1919',
    'country'        => 'Serbia',
    'departement_fr' => NULL,
    'recclass'       => 'OC',
    'mass_g'         => 212.0,
    'reclat'         => 43.83889,
    'reclong'        => 20.33333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RS',
    'id'             => 5187,
  ),
  55 =>
  array(
    'name'           => 'Cali',
    'year'           => '2007',
    'country'        => 'Colombia',
    'departement_fr' => NULL,
    'recclass'       => 'H/L4',
    'mass_g'         => 478.0,
    'reclat'         => 3.405,
    'reclong'        => -76.51,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CO',
    'id'             => 45976,
  ),
  56 =>
  array(
    'name'           => 'Campos Sales',
    'year'           => '1991',
    'country'        => 'Brazil',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 23680.0,
    'reclat'         => -7.03333,
    'reclong'        => -40.16667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'BR',
    'id'             => 5249,
  ),
  57 =>
  array(
    'name'           => 'Çanakkale',
    'year'           => '1964',
    'country'        => 'Turkey',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 4000.0,
    'reclat'         => 39.8,
    'reclong'        => 26.6,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'TR',
    'id'             => 5250,
  ),
  58 =>
  array(
    'name'           => 'Cañellas',
    'year'           => '1861',
    'country'        => 'Spain',
    'departement_fr' => 'Barcelona',
    'recclass'       => 'H4',
    'mass_g'         => 945.0,
    'reclat'         => 41.25,
    'reclong'        => 1.66667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'ES',
    'id'             => 5251,
  ),
  59 =>
  array(
    'name'           => 'Cape Girardeau',
    'year'           => '1846',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'H6',
    'mass_g'         => 2300.0,
    'reclat'         => 37.26667,
    'reclong'        => -89.58333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5260,
  ),
  60 =>
  array(
    'name'           => 'Capilla del Monte',
    'year'           => '1934',
    'country'        => 'Argentina',
    'departement_fr' => NULL,
    'recclass'       => 'H6',
    'mass_g'         => 750.0,
    'reclat'         => -30.88333,
    'reclong'        => -64.55,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AR',
    'id'             => 5264,
  ),
  61 =>
  array(
    'name'           => 'Caratash',
    'year'           => '1902',
    'country'        => 'Turkey',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 8.0,
    'reclat'         => 38.5,
    'reclong'        => 27.0,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'TR',
    'id'             => 5265,
  ),
  62 =>
  array(
    'name'           => 'Castine',
    'year'           => '1848',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 94.0,
    'reclat'         => 44.38333,
    'reclong'        => -68.75,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5293,
  ),
  63 =>
  array(
    'name'           => 'Caswell County',
    'year'           => '1810',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'OC',
    'mass_g'         => 1360.0,
    'reclat'         => 36.5,
    'reclong'        => -79.25,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5296,
  ),
  64 =>
  array(
    'name'           => 'Centerville',
    'year'           => '1956',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 45.6,
    'reclat'         => 43.2,
    'reclong'        => -96.91667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5307,
  ),
  65 =>
  array(
    'name'           => 'Chail',
    'year'           => '1814',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'H6',
    'mass_g'         => 0.5,
    'reclat'         => 25.36667,
    'reclong'        => 81.66667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 5314,
  ),
  66 =>
  array(
    'name'           => 'Chajari',
    'year'           => '1933',
    'country'        => 'Argentina',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 18300.0,
    'reclat'         => -30.78333,
    'reclong'        => -58.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AR',
    'id'             => 5316,
  ),
  67 =>
  array(
    'name'           => 'Changde',
    'year'           => '1977',
    'country'        => 'People\'s Republic of China',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 1810.0,
    'reclat'         => 29.08333,
    'reclong'        => 111.75,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CN',
    'id'             => 5322,
  ),
  68 =>
  array(
    'name'           => 'Chantonnay',
    'year'           => '1812',
    'country'        => 'France',
    'departement_fr' => 'Indre',
    'recclass'       => 'L6',
    'mass_g'         => 31500.0,
    'reclat'         => 46.68333,
    'reclong'        => 1.05,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5325,
  ),
  69 =>
  array(
    'name'           => 'Château-Renard',
    'year'           => '1841',
    'country'        => 'France',
    'departement_fr' => 'Loiret',
    'recclass'       => 'L6',
    'mass_g'         => 30000.0,
    'reclat'         => 47.93333,
    'reclong'        => 2.91667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 5332,
  ),
  70 =>
  array(
    'name'           => 'Chaves',
    'year'           => '1925',
    'country'        => 'Spain',
    'departement_fr' => 'Ourense',
    'recclass'       => 'Howardite',
    'mass_g'         => 2945.0,
    'reclat'         => 41.93333,
    'reclong'        => -7.46667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'ES',
    'id'             => 5334,
  ),
  71 =>
  array(
    'name'           => 'Chergach',
    'year'           => '2007',
    'country'        => 'Mali',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 100000.0,
    'reclat'         => 23.69639,
    'reclong'        => -5.01472,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'ML',
    'id'             => 47347,
  ),
  72 =>
  array(
    'name'           => 'Cherokee Springs',
    'year'           => '1933',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 8400.0,
    'reclat'         => 35.03333,
    'reclong'        => -81.88333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5340,
  ),
  73 =>
  array(
    'name'           => 'Chicora',
    'year'           => '1938',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 303.0,
    'reclat'         => 40.93333,
    'reclong'        => -79.73333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5349,
  ),
  74 =>
  array(
    'name'           => 'Chisenga',
    'year'           => '1988',
    'country'        => 'Malawi',
    'departement_fr' => NULL,
    'recclass'       => 'Iron, IIIAB',
    'mass_g'         => 3920.0,
    'reclat'         => -10.05944,
    'reclong'        => 33.395,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MW',
    'id'             => 5355,
  ),
  75 =>
  array(
    'name'           => 'Clohars',
    'year'           => '1822',
    'country'        => NULL,
    'departement_fr' => NULL,
    'recclass'       => 'L4',
    'mass_g'         => 48.6,
    'reclat'         => NULL,
    'reclong'        => NULL,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => NULL,
    'id'             => 5383,
    'geolocation'    => NULL,
  ),
  76 =>
  array(
    'name'           => 'Coleman',
    'year'           => '1994',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 469.0,
    'reclat'         => 43.76111,
    'reclong'        => -84.50778,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 5401,
  ),
  77 =>
  array(
    'name'           => 'Conquista',
    'year'           => '1965',
    'country'        => 'Brazil',
    'departement_fr' => NULL,
    'recclass'       => 'H4',
    'mass_g'         => 20350.0,
    'reclat'         => -19.85,
    'reclong'        => -47.55,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'BR',
    'id'             => 5418,
  ),
  78 =>
  array(
    'name'           => 'Cosina',
    'year'           => '1844',
    'country'        => 'Mexico',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 1200.0,
    'reclat'         => 21.16667,
    'reclong'        => -100.86667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'MX',
    'id'             => 5451,
  ),
  79 =>
  array(
    'name'           => 'Daule',
    'year'           => '2008',
    'country'        => 'Ecuador',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 6580.0,
    'reclat'         => -1.87089,
    'reclong'        => -79.95756,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'EC',
    'id'             => 51559,
  ),
  80 =>
  array(
    'name'           => 'Demina',
    'year'           => '1911',
    'country'        => 'Russia',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 16400.0,
    'reclat'         => 51.46667,
    'reclong'        => 84.76667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'RU',
    'id'             => 6649,
  ),
  81 =>
  array(
    'name'           => 'Denver',
    'year'           => '1967',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 230.0,
    'reclat'         => 39.7825,
    'reclong'        => -104.93056,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 6660,
  ),
  82 =>
  array(
    'name'           => 'Dergaon',
    'year'           => '2001',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 12500.0,
    'reclat'         => 26.68333,
    'reclong'        => 93.86667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 6664,
  ),
  83 =>
  array(
    'name'           => 'Devri-Khera',
    'year'           => '1994',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 1140.0,
    'reclat'         => 24.225,
    'reclong'        => 76.525,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 6696,
  ),
  84 =>
  array(
    'name'           => 'Dharwar',
    'year'           => '1848',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'OC',
    'mass_g'         => 1800.0,
    'reclat'         => 14.88333,
    'reclong'        => 75.6,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 6699,
  ),
  85 =>
  array(
    'name'           => 'Dhurmsala',
    'year'           => '1860',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 32000.0,
    'reclat'         => 32.23333,
    'reclong'        => 76.46667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 7640,
  ),
  86 =>
  array(
    'name'           => 'Didim',
    'year'           => '2007',
    'country'        => 'Turkey',
    'departement_fr' => NULL,
    'recclass'       => 'H3-5',
    'mass_g'         => 3396.0,
    'reclat'         => 37.35172,
    'reclong'        => 27.32997,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'TR',
    'id'             => 47350,
  ),
  87 =>
  array(
    'name'           => 'Dong Ujimqin Qi',
    'year'           => '1995',
    'country'        => 'People\'s Republic of China',
    'departement_fr' => NULL,
    'recclass'       => 'Mesosiderite',
    'mass_g'         => 128800.0,
    'reclat'         => 45.5,
    'reclong'        => 119.03333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CN',
    'id'             => 7706,
  ),
  88 =>
  array(
    'name'           => 'Drake Creek',
    'year'           => '1827',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'L6',
    'mass_g'         => 5000.0,
    'reclat'         => 36.4,
    'reclong'        => -86.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 7728,
  ),
  89 =>
  array(
    'name'           => 'Dubrovnik',
    'year'           => '1951',
    'country'        => 'Croatia',
    'departement_fr' => NULL,
    'recclass'       => 'L3-6',
    'mass_g'         => 1900.0,
    'reclat'         => 42.45833,
    'reclong'        => 18.44167,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'HR',
    'id'             => 7736,
  ),
  90 =>
  array(
    'name'           => 'Dyalpur',
    'year'           => '1872',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'Ureilite',
    'mass_g'         => 300.0,
    'reclat'         => 26.25,
    'reclong'        => 82.0,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 7757,
  ),
  91 =>
  array(
    'name'           => 'Ehole',
    'year'           => '1961',
    'country'        => 'Angola',
    'departement_fr' => NULL,
    'recclass'       => 'H5',
    'mass_g'         => 2400.0,
    'reclat'         => -17.3,
    'reclong'        => 15.83333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AO',
    'id'             => 7774,
  ),
  92 =>
  array(
    'name'           => 'Elbert',
    'year'           => '1998',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'LL6',
    'mass_g'         => 680.5,
    'reclat'         => 39.24667,
    'reclong'        => -104.58817,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 7822,
  ),
  93 =>
  array(
    'name'           => 'Elbogen',
    'year'           => '1399',
    'country'        => 'Czech Republic',
    'departement_fr' => NULL,
    'recclass'       => 'Iron, IID',
    'mass_g'         => 107000.0,
    'reclat'         => 50.18333,
    'reclong'        => 12.73333,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'CZ',
    'id'             => 7823,
  ),
  94 =>
  array(
    'name'           => 'Elenovka',
    'year'           => '1951',
    'country'        => 'Ukraine',
    'departement_fr' => NULL,
    'recclass'       => 'L5',
    'mass_g'         => 54640.0,
    'reclat'         => 47.83333,
    'reclong'        => 37.66667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'UA',
    'id'             => 7824,
  ),
  95 =>
  array(
    'name'           => 'Emmaville',
    'year'           => '1900',
    'country'        => 'Australia',
    'departement_fr' => 'Glen Innes Severn',
    'recclass'       => 'Eucrite-mmict',
    'mass_g'         => 127.0,
    'reclat'         => -29.46667,
    'reclong'        => 151.61667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AU',
    'id'             => 10033,
  ),
  96 =>
  array(
    'name'           => 'Ensisheim',
    'year'           => '1491',
    'country'        => 'France',
    'departement_fr' => 'Haut-Rhin',
    'recclass'       => 'LL6',
    'mass_g'         => 127000.0,
    'reclat'         => 47.86667,
    'reclong'        => 7.35,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'FR',
    'id'             => 10039,
  ),
  97 =>
  array(
    'name'           => 'Erakot',
    'year'           => '1940',
    'country'        => 'India',
    'departement_fr' => NULL,
    'recclass'       => 'CM2',
    'mass_g'         => 113.0,
    'reclat'         => 19.03333,
    'reclong'        => 81.89167,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'IN',
    'id'             => 10042,
  ),
  98 =>
  array(
    'name'           => 'Erevan',
    'year'           => '1911',
    'country'        => 'Armenia',
    'departement_fr' => NULL,
    'recclass'       => 'Howardite',
    'mass_g'         => 107.2,
    'reclat'         => 40.3,
    'reclong'        => 44.5,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'AM',
    'id'             => 10043,
  ),
  99 =>
  array(
    'name'           => 'Fayetteville',
    'year'           => '1934',
    'country'        => 'United States of America',
    'departement_fr' => NULL,
    'recclass'       => 'H4',
    'mass_g'         => 2360.0,
    'reclat'         => 36.05,
    'reclong'        => -94.16667,
    'nametype'       => 'Valid',
    'fall'           => 'Fell',
    'country_code'   => 'US',
    'id'             => 10079,
  ),
);
?>