const employésGammaSolution = [
  {
    prénom: "Michel",
    NOM: "DUPONT",
    salaire: 4887,
    "salaire annuelle": 59244,
  },
  {
    prénom: "Laurent",
    NOM: "ROBERT",
    salaire: 4852,
    "salaire annuelle": 58824,
  },
  {
    prénom: "Kevin",
    NOM: "MOREAU",
    salaire: 4844,
    "salaire annuelle": 58728,
  },
  {
    prénom: "Anthony",
    NOM: "GIRARD",
    salaire: 4798,
    "salaire annuelle": 58176,
  },
  {
    prénom: "Julien",
    NOM: "THOMAS",
    salaire: 4793,
    "salaire annuelle": 58116,
  },
  {
    prénom: "Anthony",
    NOM: "FOURNIER",
    salaire: 4722,
    "salaire annuelle": 57264,
  },
  {
    prénom: "Emilie",
    NOM: "LEMAIRE",
    salaire: 4685,
    "salaire annuelle": 56820,
  },
  {
    prénom: "Pierre",
    NOM: "THOMAS",
    salaire: 4631,
    "salaire annuelle": 56172,
  },
  {
    prénom: "Michel",
    NOM: "GIRARD",
    salaire: 4582,
    "salaire annuelle": 55584,
  },
  {
    prénom: "Marie",
    NOM: "FOURNIER",
    salaire: 4574,
    "salaire annuelle": 55488,
  },
  {
    prénom: "Emilie",
    NOM: "ROBERT",
    salaire: 4544,
    "salaire annuelle": 55128,
  },
  {
    prénom: "Jacques",
    NOM: "DURAND",
    salaire: 4529,
    "salaire annuelle": 54948,
  },
  {
    prénom: "Laurent",
    NOM: "DUPONT",
    salaire: 4523,
    "salaire annuelle": 54876,
  },
  {
    prénom: "Michel",
    NOM: "ROBERT",
    salaire: 4501,
    "salaire annuelle": 54612,
  },
  {
    prénom: "Pierre",
    NOM: "BERTRAND",
    salaire: 4464,
    "salaire annuelle": 54168,
  },
  {
    prénom: "Marie",
    NOM: "MARTIN",
    salaire: 4423,
    "salaire annuelle": 53676,
  },
  {
    prénom: "Aurélie",
    NOM: "PETIT",
    salaire: 4412,
    "salaire annuelle": 53544,
  },
  {
    prénom: "François",
    NOM: "BERTRAND",
    salaire: 4392,
    "salaire annuelle": 53304,
  },
  {
    prénom: "Julien",
    NOM: "THOMAS",
    salaire: 4305,
    "salaire annuelle": 52260,
  },
  {
    prénom: "Michel",
    NOM: "LEFEBVRE",
    salaire: 4207,
    "salaire annuelle": 51084,
  },
  {
    prénom: "Jacques",
    NOM: "GIRARD",
    salaire: 4184,
    "salaire annuelle": 50808,
  },
  {
    prénom: "Anthony",
    NOM: "DUPONT",
    salaire: 4128,
    "salaire annuelle": 50136,
  },
  {
    prénom: "André",
    NOM: "RICHARD",
    salaire: 4092,
    "salaire annuelle": 49704,
  },
  {
    prénom: "Jacques",
    NOM: "FOURNIER",
    salaire: 4090,
    "salaire annuelle": 49680,
  },
  {
    prénom: "Jean",
    NOM: "LEROY",
    salaire: 4037,
    "salaire annuelle": 49044,
  },
  {
    prénom: "Marc",
    NOM: "GIRARD",
    salaire: 4032,
    "salaire annuelle": 48984,
  },
  {
    prénom: "Julien",
    NOM: "ROBERT",
    salaire: 3971,
    "salaire annuelle": 48252,
  },
  {
    prénom: "Jean",
    NOM: "DUPONT",
    salaire: 3946,
    "salaire annuelle": 47952,
  },
  {
    prénom: "François",
    NOM: "LEMAIRE",
    salaire: 3856,
    "salaire annuelle": 46872,
  },
  {
    prénom: "Aurélie",
    NOM: "LEROY",
    salaire: 3837,
    "salaire annuelle": 46644,
  },
  {
    prénom: "Emilie",
    NOM: "LEMAIRE",
    salaire: 3775,
    "salaire annuelle": 45900,
  },
  {
    prénom: "Jacques",
    NOM: "GIRARD",
    salaire: 3773,
    "salaire annuelle": 45876,
  },
  {
    prénom: "Michel",
    NOM: "RICHARD",
    salaire: 3730,
    "salaire annuelle": 45360,
  },
  {
    prénom: "Jean",
    NOM: "BERTRAND",
    salaire: 3721,
    "salaire annuelle": 45252,
  },
  {
    prénom: "Marc",
    NOM: "THOMAS",
    salaire: 3698,
    "salaire annuelle": 44976,
  },
  {
    prénom: "Pierre",
    NOM: "RICHARD",
    salaire: 3696,
    "salaire annuelle": 44952,
  },
  {
    prénom: "Laurent",
    NOM: "LEFEBVRE",
    salaire: 3621,
    "salaire annuelle": 44052,
  },
  {
    prénom: "François",
    NOM: "DUBOIS",
    salaire: 3599,
    "salaire annuelle": 43788,
  },
  {
    prénom: "Jean",
    NOM: "GIRARD",
    salaire: 3553,
    "salaire annuelle": 43236,
  },
  {
    prénom: "Jacques",
    NOM: "PETIT",
    salaire: 3528,
    "salaire annuelle": 42936,
  },
  {
    prénom: "François",
    NOM: "DURAND",
    salaire: 3487,
    "salaire annuelle": 42444,
  },
  {
    prénom: "François",
    NOM: "DUPONT",
    salaire: 3444,
    "salaire annuelle": 41928,
  },
  {
    prénom: "Emilie",
    NOM: "MOREAU",
    salaire: 3403,
    "salaire annuelle": 41436,
  },
  {
    prénom: "Marie",
    NOM: "LEFEBVRE",
    salaire: 3372,
    "salaire annuelle": 41064,
  },
  {
    prénom: "Pierre",
    NOM: "PETIT",
    salaire: 3369,
    "salaire annuelle": 41028,
  },
  {
    prénom: "Jean",
    NOM: "LEFEBVRE",
    salaire: 3293,
    "salaire annuelle": 40116,
  },
  {
    prénom: "Marie",
    NOM: "DUPONT",
    salaire: 3225,
    "salaire annuelle": 39300,
  },
  {
    prénom: "Pierre",
    NOM: "FOURNIER",
    salaire: 3207,
    "salaire annuelle": 39084,
  },
  {
    prénom: "François",
    NOM: "DUPONT",
    salaire: 3186,
    "salaire annuelle": 38832,
  },
  {
    prénom: "Jean",
    NOM: "ROBERT",
    salaire: 3172,
    "salaire annuelle": 38664,
  },
  {
    prénom: "François",
    NOM: "MOREAU",
    salaire: 3117,
    "salaire annuelle": 38004,
  },
  {
    prénom: "Anthony",
    NOM: "LEFEBVRE",
    salaire: 3110,
    "salaire annuelle": 37920,
  },
  {
    prénom: "Aurélie",
    NOM: "THOMAS",
    salaire: 3098,
    "salaire annuelle": 37776,
  },
  {
    prénom: "Kevin",
    NOM: "LEFEBVRE",
    salaire: 3088,
    "salaire annuelle": 37656,
  },
  {
    prénom: "Jean",
    NOM: "ROBERT",
    salaire: 3084,
    "salaire annuelle": 37608,
  },
  {
    prénom: "Marie",
    NOM: "MARTIN",
    salaire: 3075,
    "salaire annuelle": 37500,
  },
  {
    prénom: "Laurent",
    NOM: "LEMAIRE",
    salaire: 3000,
    "salaire annuelle": 36600,
  },
  {
    prénom: "Jean",
    NOM: "THOMAS",
    salaire: 2954,
    "salaire annuelle": 36048,
  },
  {
    prénom: "Pierre",
    NOM: "THOMAS",
    salaire: 2928,
    "salaire annuelle": 35736,
  },
  {
    prénom: "Julien",
    NOM: "MARTIN",
    salaire: 2884,
    "salaire annuelle": 35208,
  },
  {
    prénom: "Marc",
    NOM: "LEROY",
    salaire: 2794,
    "salaire annuelle": 34128,
  },
  {
    prénom: "Jean",
    NOM: "BERTRAND",
    salaire: 2731,
    "salaire annuelle": 33372,
  },
  {
    prénom: "Emilie",
    NOM: "MARTIN",
    salaire: 2692,
    "salaire annuelle": 32904,
  },
  {
    prénom: "Anthony",
    NOM: "MOREAU",
    salaire: 2628,
    "salaire annuelle": 32136,
  },
  {
    prénom: "Kevin",
    NOM: "LEFEBVRE",
    salaire: 2605,
    "salaire annuelle": 31860,
  },
  {
    prénom: "Jacques",
    NOM: "LEMAIRE",
    salaire: 2584,
    "salaire annuelle": 31608,
  },
  {
    prénom: "Jean",
    NOM: "RICHARD",
    salaire: 2577,
    "salaire annuelle": 31524,
  },
  {
    prénom: "Sophie",
    NOM: "FOURNIER",
    salaire: 2563,
    "salaire annuelle": 31356,
  },
  {
    prénom: "Marc",
    NOM: "MARTIN",
    salaire: 2541,
    "salaire annuelle": 31092,
  },
  {
    prénom: "Emilie",
    NOM: "RICHARD",
    salaire: 2477,
    "salaire annuelle": 30324,
  },
  {
    prénom: "Anthony",
    NOM: "LEROY",
    salaire: 2375,
    "salaire annuelle": 29100,
  },
  {
    prénom: "Kevin",
    NOM: "LEFEBVRE",
    salaire: 2370,
    "salaire annuelle": 29040,
  },
  {
    prénom: "François",
    NOM: "DURAND",
    salaire: 2327,
    "salaire annuelle": 28524,
  },
  {
    prénom: "Julien",
    NOM: "RICHARD",
    salaire: 2274,
    "salaire annuelle": 27888,
  },
  {
    prénom: "Emilie",
    NOM: "LEFEBVRE",
    salaire: 2212,
    "salaire annuelle": 27144,
  },
  {
    prénom: "André",
    NOM: "FOURNIER",
    salaire: 2189,
    "salaire annuelle": 26868,
  },
  {
    prénom: "Sophie",
    NOM: "MOREAU",
    salaire: 2171,
    "salaire annuelle": 26652,
  },
  {
    prénom: "Pierre",
    NOM: "GIRARD",
    salaire: 2116,
    "salaire annuelle": 25992,
  },
  {
    prénom: "Jean",
    NOM: "MOREAU",
    salaire: 2023,
    "salaire annuelle": 24876,
  },
  {
    prénom: "François",
    NOM: "GIRARD",
    salaire: 2018,
    "salaire annuelle": 24816,
  },
  {
    prénom: "Marc",
    NOM: "FOURNIER",
    salaire: 2013,
    "salaire annuelle": 24756,
  },
  {
    prénom: "Marie",
    NOM: "RICHARD",
    salaire: 2009,
    "salaire annuelle": 24708,
  },
  {
    prénom: "Jean",
    NOM: "RICHARD",
    salaire: 2003,
    "salaire annuelle": 24636,
  },
  {
    prénom: "Laurent",
    NOM: "ROBERT",
    salaire: 2001,
    "salaire annuelle": 24612,
  },
  {
    prénom: "André",
    NOM: "RICHARD",
    salaire: 1951,
    "salaire annuelle": 24012,
  },
  {
    prénom: "Marie",
    NOM: "BERTRAND",
    salaire: 1931,
    "salaire annuelle": 23772,
  },
  {
    prénom: "Julien",
    NOM: "DUBOIS",
    salaire: 1916,
    "salaire annuelle": 23592,
  },
  {
    prénom: "Julien",
    NOM: "MOREAU",
    salaire: 1897,
    "salaire annuelle": 23364,
  },
  {
    prénom: "André",
    NOM: "DUPONT",
    salaire: 1887,
    "salaire annuelle": 23244,
  },
  {
    prénom: "Marc",
    NOM: "PETIT",
    salaire: 1872,
    "salaire annuelle": 23064,
  },
  {
    prénom: "Jean",
    NOM: "FOURNIER",
    salaire: 1862,
    "salaire annuelle": 22944,
  },
  {
    prénom: "Michel",
    NOM: "DURAND",
    salaire: 1786,
    "salaire annuelle": 22032,
  },
  {
    prénom: "Marc",
    NOM: "DURAND",
    salaire: 1775,
    "salaire annuelle": 21900,
  },
  {
    prénom: "Michel",
    NOM: "RICHARD",
    salaire: 1747,
    "salaire annuelle": 21564,
  },
  {
    prénom: "Kevin",
    NOM: "GIRARD",
    salaire: 1743,
    "salaire annuelle": 21516,
  },
  {
    prénom: "François",
    NOM: "DUPONT",
    salaire: 1739,
    "salaire annuelle": 21468,
  },
  {
    prénom: "François",
    NOM: "FOURNIER",
    salaire: 1702,
    "salaire annuelle": 21024,
  },
  {
    prénom: "Jean",
    NOM: "GIRARD",
    salaire: 1617,
    "salaire annuelle": 20004,
  },
  {
    prénom: "Sophie",
    NOM: "GIRARD",
    salaire: 1593,
    "salaire annuelle": 19716,
  },
  {
    prénom: "Jacques",
    NOM: "THOMAS",
    salaire: 1561,
    "salaire annuelle": 19332,
  },
  {
    prénom: "Julien",
    NOM: "LEFEBVRE",
    salaire: 1539,
    "salaire annuelle": 19068,
  },
  {
    prénom: "Kevin",
    NOM: "PETIT",
    salaire: 1528,
    "salaire annuelle": 18936,
  },
  {
    prénom: "Mélanie",
    NOM: "RICHARD",
    salaire: 1520,
    "salaire annuelle": 18840,
  },
  {
    prénom: "Jean",
    NOM: "THOMAS",
    salaire: 1476,
    "salaire annuelle": 18312,
  },
  {
    prénom: "Kevin",
    NOM: "LEFEBVRE",
    salaire: 1421,
    "salaire annuelle": 17652,
  },
  {
    prénom: "Marc",
    NOM: "MOREAU",
    salaire: 1320,
    "salaire annuelle": 16440,
  },
  {
    prénom: "Michel",
    NOM: "FOURNIER",
    salaire: 1268,
    "salaire annuelle": 15816,
  },
  {
    prénom: "Jean",
    NOM: "LEROY",
    salaire: 1232,
    "salaire annuelle": 15384,
  },
  {
    prénom: "Marc",
    NOM: "LEMAIRE",
    salaire: 1190,
    "salaire annuelle": 14880,
  },
  {
    prénom: "Laurent",
    NOM: "MARTIN",
    salaire: 1126,
    "salaire annuelle": 14112,
  },
];
